### ISSUE TITLE
Vagrant Error !!!

### ISSUE THREAD

**Issue by Narasimha1337** [gauntlt/gauntlt-starter-kit#11]
default: - yum (1.0.0)
==> default: Installing Cookbook Gems:
==> default: Compiling Cookbooks...
==> default: 
==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/build-essential/attributes/default.rb
==> default: ================================================================================
==> default: 
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: 
==> default: undefined method `platform' for #<Chef::Node::Attribute:0x00000003377118>
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/build-essential/attributes/default.rb:22:in `from_file'
==> default: 
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/build-essential/attributes/default.rb:
==> default: 
==> default:  15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
==> default:  16:  # See the License for the specific language governing permissions and
==> default:  17:  # limitations under the License.
==> default:  18:  #
==> default:  19:  
==> default:  20:  default['build_essential']['compiletime'] = false
==> default:  21:  
==> default:  22>> case platform
==> default:  23:  when "mac_os_x"
==> default:  24:    case
==> default:  25:    when Chef::VersionConstraint.new("~> 10.7.0").include?(platform_version),
==> default:  26:         Chef::VersionConstraint.new("~> 10.8.0").include?(platform_version)
==> default:  27:      default['build_essential']['osx']['gcc_installer_url'] = "https://github.com/downloads/kennethreitz/osx-gcc-installer/GCC-10.7-v2.pkg"
==> default:  28:      default['build_essential']['osx']['gcc_installer_checksum'] = "df36aa87606feb99d0db9ac9a492819e"
==> default:  29:    when Chef::VersionConstraint.new("~> 10.6.0").include?(platform_version)
==> default:  30:      default['build_essential']['osx']['gcc_installer_url'] = "https://github.com/downloads/kennethreitz/osx-gcc-installer/GCC-10.6.pkg"
==> default:  31:      default['build_essential']['osx']['gcc_installer_checksum'] = "d1db5bab6a3f6b9f3b5577a130baeefa"
==> default: 
==> default: System Info:
==> default: ------------
==> default: chef_version=13.1.31
==> default: platform=ubuntu
==> default: platform_version=14.04
==> default: ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
==> default: program_name=chef-solo worker: ppid=2613;start=17:20:45;
==> default: executable=/opt/chef/bin/chef-solo
==> default: 
==> default: 
==> default: 
==> default: Running handlers:
==> default: [2017-06-12T17:20:59+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: 
==> default: [2017-06-12T17:20:59+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 13 seconds
==> default: [2017-06-12T17:20:59+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-06-12T17:20:59+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-06-12T17:20:59+00:00] ERROR: undefined method `platform' for #<Chef::Node::Attribute:0x00000003377118>
==> default: [2017-06-12T17:20:59+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
root@root:~/Desktop/gauntlt-starter-kit/vagrant/gauntlt#  Recipe Compile Error in /var/chef/cache/cookbooks/build-essential/attributes/default.rb

**Comment by jahbenjah** [comment]
Hey @Murthysagi! Do you solve this issue?
I'm experiencing the same.
